C:\Users\khine_qeb1xlm\AppData\Local\Programs\Python\Python37\python.exe C:\Users\khine_qeb1xlm\Desktop\prj1\main.py
pygame 2.5.2 (SDL 2.28.3, Python 3.7.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
None
INFO: listening to server 127.0.0.1:2000
INFO:  Found the required file in cache!  Carla/Maps/Nav/Town10HD_Opt.bin
INFO:  Found the required file in cache!  Carla/Maps/TM/Town10HD_Opt.bin
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=16, type=traffic.traffic_light)- Red
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Green
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=15, type=traffic.traffic_light)- Yellow
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Actor(id=23, type=traffic.traffic_light)- Red
Location(x=-47.555183, y=35.115948, z=0.038772)
Vector3D(x=-47.026634, y=75.112457, z=0.038772)
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=21, type=traffic.traffic_light)- Red
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Actor(id=22, type=traffic.traffic_light)- Green
Location(x=-99.107124, y=102.363708, z=0.038609)
Vector3D(x=-114.475327, y=65.433807, z=0.038609)
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=18, type=traffic.traffic_light)- Red
Actor(id=17, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Yellow
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=9, type=traffic.traffic_light)- Red
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=19, type=traffic.traffic_light)- Green
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Location(x=-61.335102, y=-63.087124, z=0.038872)
Vector3D(x=-24.410709, y=-47.705662, z=0.038872)
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=11, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Actor(id=12, type=traffic.traffic_light)- Red
Location(x=19.148802, y=-62.922943, z=0.038927)
Vector3D(x=53.196953, y=-41.929527, z=0.038927)
Location(x=80.534050, y=-59.317394, z=0.038728)
Vector3D(x=118.417175, y=-46.477276, z=0.038728)
Actor(id=14, type=traffic.traffic_light)- Red
Actor(id=14, type=traffic.traffic_light)- Red
Actor(id=14, type=traffic.traffic_light)- Red
Actor(id=14, type=traffic.traffic_light)- Red
Actor(id=14, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=13, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Yellow
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Actor(id=10, type=traffic.traffic_light)- Red
Location(x=94.603027, y=119.099487, z=0.038875)
Vector3D(x=75.207458, y=154.082520, z=0.038875)
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Green
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow
Actor(id=21, type=traffic.traffic_light)- Yellow

Process finished with exit code 0
__________________________
vehicle
location: Location(x=-31.033264, y=-53.138508, z=0.217276)
vehicle
forward: Vector3D(x=0.999129, y=-0.041736, z=-0.000355)
light
location: Location(x=-119.230034, y=5.093152, z=0.262770)
105.68632507324219
Actor(id=9, type=traffic.traffic_light)
Red
light
location: Location(x=115.449829, y=35.044945, z=0.222726)
170.97842407226562
Actor(id=10, type=traffic.traffic_light)
Red
light
location: Location(x=-46.171577, y=-73.556618, z=0.254254)
25.417888641357422
Actor(id=11, type=traffic.traffic_light)
Red
light
location: Location(x=-34.449154, y=-51.020489, z=0.254255)
4.019412517547607
Actor(id=12, type=traffic.traffic_light)
Red
light
location: Location(x=114.451889, y=21.196003, z=0.254200)
163.37548828125
Actor(id=13, type=traffic.traffic_light)
Red
light
location: Location(x=89.791885, y=20.922146, z=0.254200)
141.7169647216797
Actor(id=14, type=traffic.traffic_light)
Red
light
location: Location(x=-31.930841, y=20.301954, z=0.254254)
73.44595336914062
Actor(id=15, type=traffic.traffic_light)
Red
light
location: Location(x=-64.264191, y=7.063309, z=0.254254)
68.76448822021484
Actor(id=16, type=traffic.traffic_light)
Red
light
location: Location(x=-62.352070, y=20.196909, z=0.254254)
79.7430419921875
Actor(id=17, type=traffic.traffic_light)
Red
light
location: Location(x=-94.928223, y=20.334822, z=0.254256)
97.3698959350586
Actor(id=18, type=traffic.traffic_light)
Red
light
location: Location(x=-59.242249, y=-51.498371, z=0.254254)
28.256649017333984
Actor(id=19, type=traffic.traffic_light)
Red
light
location: Location(x=-119.238182, y=19.004469, z=0.254253)
113.95050811767578
Actor(id=20, type=traffic.traffic_light)
Red
light
location: Location(x=-58.715359, y=145.824570, z=0.254188)
200.8795623779297
Actor(id=21, type=traffic.traffic_light)
Red
light
location: Location(x=-62.099304, y=123.755508, z=0.283086)
179.60121154785156
Actor(id=22, type=traffic.traffic_light)
Red
light
location: Location(x=-31.636356, y=33.589287, z=0.254254)
86.72990417480469
Actor(id=23, type=traffic.traffic_light)
Red
__________________________
